import { Article, Category, User } from '../types';

export const mockUser: User = {
  id: '1',
  username: '爱米',
  email: 'aimi@example.com',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
};

export const mockCategories: Category[] = [
  { id: '1', name: 'React', slug: 'react', color: '#61DAFB' },
  { id: '2', name: 'Vue', slug: 'vue', color: '#4FC08D' },
  { id: '3', name: 'JavaScript', slug: 'javascript', color: '#F7DF1E' },
  { id: '4', name: 'CSS', slug: 'css', color: '#1572B6' },
  { id: '5', name: 'TypeScript', slug: 'typescript', color: '#3178C6' },
  { id: '6', name: 'Node.js', slug: 'nodejs', color: '#339933' },
];

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'React 18 新特性深度解析：并发渲染与自动批处理',
    summary: 'React 18 引入了并发渲染机制，让应用能够保持响应性并优雅地处理大型渲染任务。本文将深入探讨并发渲染的工作原理、自动批处理优化以及如何在实际项目中应用这些新特性。',
    content: 'React 18 是 React 的一个重大版本更新，带来了许多激动人心的新特性...',
    category: 'React',
    tags: ['React', 'Concurrent Rendering', 'Performance', 'JavaScript'],
    author: mockUser,
    createdAt: '2024-11-20T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
  },
  {
    id: '2',
    title: 'Vue 3 Composition API 最佳实践指南',
    summary: 'Vue 3 的 Composition API 提供了更灵活的代码组织方式。本文将分享在实际项目中使用 Composition API 的最佳实践，包括逻辑复用、状态管理和性能优化技巧。',
    content: 'Vue 3 引入的 Composition API 是对 Options API 的有力补充...',
    category: 'Vue',
    tags: ['Vue', 'Composition API', 'Best Practices', 'Frontend'],
    author: mockUser,
    createdAt: '2024-11-18T14:30:00Z',
    updatedAt: '2024-11-18T14:30:00Z',
  },
  {
    id: '3',
    title: '现代 CSS 布局技术：Grid 与 Flexbox 实战对比',
    summary: 'CSS Grid 和 Flexbox 是现代网页布局的两大利器。本文通过实际案例对比分析两种布局技术的适用场景，帮助你选择最合适的布局方案。',
    content: '在现代前端开发中，CSS Grid 和 Flexbox 已经成为布局的标准...',
    category: 'CSS',
    tags: ['CSS', 'Grid', 'Flexbox', 'Layout', 'Frontend'],
    author: mockUser,
    createdAt: '2024-11-15T09:15:00Z',
    updatedAt: '2024-11-15T09:15:00Z',
  },
  {
    id: '4',
    title: 'TypeScript 高级类型系统：条件类型与映射类型',
    summary: '深入探讨 TypeScript 的高级类型特性，包括条件类型、映射类型、模板字面量类型等。通过实际案例展示如何利用这些特性构建更类型安全的应用。',
    content: 'TypeScript 的类型系统非常强大，特别是其高级类型特性...',
    category: 'TypeScript',
    tags: ['TypeScript', 'Advanced Types', 'Conditional Types', 'Mapped Types'],
    author: mockUser,
    createdAt: '2024-11-12T16:45:00Z',
    updatedAt: '2024-11-12T16:45:00Z',
  },
  {
    id: '5',
    title: 'JavaScript 异步编程：从回调到 Async/Await 的演进之路',
    summary: '回顾 JavaScript 异步编程的发展历程，从回调地狱到 Promise，再到 Async/Await。理解每种方案的优缺点，掌握现代异步编程的最佳实践。',
    content: 'JavaScript 的异步编程经历了几个重要的发展阶段...',
    category: 'JavaScript',
    tags: ['JavaScript', 'Async', 'Promise', 'Async/Await', 'Tutorial'],
    author: mockUser,
    createdAt: '2024-11-10T11:20:00Z',
    updatedAt: '2024-11-10T11:20:00Z',
  },
  {
    id: '6',
    title: 'Node.js 性能优化：内存管理与事件循环调优',
    summary: '深入分析 Node.js 应用的性能瓶颈，包括内存泄漏检测、事件循环监控和优化策略。提供实用的性能调优工具和技巧。',
    content: 'Node.js 应用的性能优化是一个复杂的话题...',
    category: 'Node.js',
    tags: ['Node.js', 'Performance', 'Memory Management', 'Event Loop'],
    author: mockUser,
    createdAt: '2024-11-08T13:10:00Z',
    updatedAt: '2024-11-08T13:10:00Z',
  },
];